"""UML class diagram / architecture diagram -> code skeletons (only what the diagram shows)."""

from __future__ import annotations

import re

from .exprs import RESERVED

IND = "    "


def _safe(name: str) -> str:
    return name + "_" if name in RESERVED else name


def _snake(name: str) -> str:
    s = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name).lower()
    return _safe(s)


def _camel(name: str) -> str:
    return _safe(name[:1].lower() + name[1:])


def _kind(t: str, class_names: set[str]) -> str:
    base = (t or "").strip()
    low = base.lower()
    if low in ("int", "integer", "long", "short", "number", "byte"):
        return "int"
    if low in ("float", "double", "decimal", "real"):
        return "float"
    if low in ("string", "str", "text", "char"):
        return "str"
    if low in ("bool", "boolean"):
        return "bool"
    if low in ("void", "none", ""):
        return "void" if low else "unknown"
    if base in class_names:
        return "class:" + base
    return "unknown"


def _parents(ir: dict) -> dict[str, dict[str, list[str]]]:
    cls = {c["name"]: c for c in ir["classes"]}
    p = {n: {"extends": [], "implements": []} for n in cls}
    for r in ir["relationships"]:
        if r["type"] in ("inheritance", "realization"):
            child, parent = r["from"], r["to"]
            if cls[parent]["stereotype"] == "interface" and cls[child]["stereotype"] != "interface":
                p[child]["implements"].append(parent)
            else:
                p[child]["extends"].append(parent)
    return p


def _ordered(ir: dict, parents: dict) -> list[dict]:
    cls = {c["name"]: c for c in ir["classes"]}
    order, seen = [], set()

    def visit(n: str):
        if n in seen:
            return
        seen.add(n)
        for par in parents[n]["extends"] + parents[n]["implements"]:
            visit(par)
        order.append(cls[n])

    for c in ir["classes"]:
        visit(c["name"])
    return order


def _add_interface_stubs(ordered: list[dict], ir: dict, parents: dict) -> list[dict]:
    """A concrete class must declare the methods of the interfaces it implements (required
    signatures only; the bodies stay placeholders)."""
    cls = {c["name"]: c for c in ir["classes"]}
    result = []
    for c in ordered:
        if c["stereotype"] != "class":
            result.append(c)
            continue
        wanted, queue, visited = [], list(parents[c["name"]]["implements"]), set()
        while queue:
            iface = queue.pop(0)
            if iface in visited:
                continue
            visited.add(iface)
            wanted += cls[iface]["methods"]
            queue += parents[iface]["extends"] + parents[iface]["implements"]
        have = {(m["name"], len(m["params"])) for m in c["methods"]}
        extra = []
        for m in wanted:
            key = (m["name"], len(m["params"]))
            if key not in have:
                have.add(key)
                extra.append({**m, "visibility": "public"})
        result.append({**c, "methods": c["methods"] + extra} if extra else c)
    return result


def _notes(ir: dict, cname: str) -> list[str]:
    out = []
    for r in ir["relationships"]:
        if r["from"] == cname and r["type"] not in ("inheritance", "realization"):
            out.append(f"{r['type'].capitalize()}: {cname} -> {r['to']}" + (f" ({r['label']})" if r["label"] else ""))
    return out


# =========================================================================== UML
def render_uml(ir: dict, language: str, requirement: str = "") -> str:
    classes = ir["classes"]
    names = {c["name"] for c in classes}
    parents = _parents(ir)
    ordered = _add_interface_stubs(_ordered(ir, parents), ir, parents)
    fn = {"python": _uml_python, "java": _uml_java, "cpp": _uml_cpp, "c": _uml_c, "javascript": _uml_js}[language]
    return fn(ordered, names, parents, ir)


def _req_header(language: str) -> list[str]:
    c = "#" if language == "python" else "//"
    return [f"{c} Skeleton generated by Syntax AI from a UML class diagram.",
            f"{c} Method bodies are placeholders: the diagram does not describe behaviour."]


def _uml_python(ordered, names, parents, ir):
    def ann(t):
        k = _kind(t, names)
        return {"int": "int", "float": "float", "str": "str", "bool": "bool", "void": "None"}.get(k) or (
            k.split(":")[1] if k.startswith("class:") else "Any")

    uses_any = any(ann(x["type"]) == "Any" for c in ordered for x in c["attributes"])
    uses_any = uses_any or any(ann(m["return_type"]) == "Any" or any(ann(p["type"]) == "Any" for p in m["params"])
                               for c in ordered for m in c["methods"])
    uses_abc = any(c["stereotype"] in ("interface", "abstract") for c in ordered)
    lines = ['"""Skeleton generated by Syntax AI from a UML class diagram.',
             'Method bodies are placeholders: the diagram does not describe behaviour."""',
             "from __future__ import annotations", ""]
    if uses_abc:
        lines.append("from abc import ABC, abstractmethod")
    if uses_any:
        lines.append("from typing import Any")
    if uses_abc or uses_any:
        lines.append("")
    for c in ordered:
        par = parents[c["name"]]["extends"] + parents[c["name"]]["implements"]
        bases = par or (["ABC"] if c["stereotype"] in ("interface", "abstract") else [])
        lines += ["", "", f"class {c['name']}" + (f"({', '.join(bases)})" if bases else "") + ":"]
        for n in _notes(ir, c["name"]):
            lines.append(f"{IND}# {n}")
        body = False
        if c["attributes"] or par:
            lines.append("")
            lines.append(f"{IND}def __init__(self):")
            if par:
                lines.append(f"{IND*2}super().__init__()")
            for a in c["attributes"]:
                lines.append(f"{IND*2}self.{_safe(a['name'])} = None  # {a['type'] or 'unspecified'} ({a['visibility']})")
            if not c["attributes"] and not par:
                lines.append(f"{IND*2}pass")
            body = True
        for m in c["methods"]:
            params = "".join(f", {_safe(p['name'])}: {ann(p['type'])}" for p in m["params"])
            lines.append("")
            if c["stereotype"] == "interface":
                lines.append(f"{IND}@abstractmethod")
            lines.append(f"{IND}def {_safe(m['name'])}(self{params}) -> {ann(m['return_type'])}:")
            lines.append(f'{IND*2}raise NotImplementedError("{c["name"]}.{m["name"]}")')
            body = True
        if not body and not _notes(ir, c["name"]):
            lines.append(f"{IND}pass")
        elif not body:
            lines.append(f"{IND}pass")
    return "\n".join(lines) + "\n"


def _uml_java(ordered, names, parents, ir):
    def jt(t):
        k = _kind(t, names)
        return {"int": "int", "float": "double", "str": "String", "bool": "boolean", "void": "void"}.get(k) or (
            k.split(":")[1] if k.startswith("class:") else "Object")

    vis = {"public": "public ", "private": "private ", "protected": "protected ", "package": ""}
    lines = _req_header("java") + [""]
    for c in ordered:
        par = parents[c["name"]]
        is_iface = c["stereotype"] == "interface"
        kw = "interface" if is_iface else ("abstract class" if c["stereotype"] == "abstract" else "class")
        head = f"{kw} {c['name']}"
        if par["extends"]:
            if is_iface:
                head += " extends " + ", ".join(par["extends"] + par["implements"])
            else:
                head += f" extends {par['extends'][0]}"
        if par["implements"] and not is_iface:
            head += " implements " + ", ".join(par["implements"])
        lines.append(head + " {")
        for extra in par["extends"][1:] if not is_iface else []:
            lines.append(f"{IND}// Also inherits from {extra} (Java allows one superclass; adapt manually)")
        for n in _notes(ir, c["name"]):
            lines.append(f"{IND}// {n}")
        for a in c["attributes"]:
            if is_iface:
                lines.append(f"{IND}// attribute (not valid in a Java interface): {a['name']}")
            else:
                lines.append(f"{IND}{vis[a['visibility']]}{jt(a['type'])} {_safe(a['name'])};")
        for m in c["methods"]:
            params = ", ".join(f"{jt(p['type'])} {_safe(p['name'])}" for p in m["params"])
            sig = f"{jt(m['return_type'])} {_safe(m['name'])}({params})"
            if is_iface:
                lines.append(f"{IND}{sig};")
            else:
                lines.append(f"{IND}{vis[m['visibility']]}{sig} {{")
                lines.append(f'{IND*2}throw new UnsupportedOperationException("Not implemented: {c["name"]}.{m["name"]}");')
                lines.append(f"{IND}}}")
        lines += ["}", ""]
    return "\n".join(lines)


def _uml_cpp(ordered, names, parents, ir):
    def ct(t):
        k = _kind(t, names)
        return {"int": "int", "float": "double", "str": "std::string", "bool": "bool", "void": "void"}.get(k) or (
            k.split(":")[1] + "*" if k.startswith("class:") else "void*")

    lines = _req_header("cpp") + ["", "#include <stdexcept>", "#include <string>", ""]
    lines += [f"class {c['name']};" for c in ordered] + [""]
    has_children = {p for c in ordered for p in parents[c["name"]]["extends"] + parents[c["name"]]["implements"]}
    for c in ordered:
        par = parents[c["name"]]["extends"] + parents[c["name"]]["implements"]
        is_iface = c["stereotype"] == "interface"
        head = f"class {c['name']}" + (" : " + ", ".join(f"public {p}" for p in par) if par else "") + " {"
        lines.append(head)
        for n in _notes(ir, c["name"]):
            lines.append(f"{IND}// {n}")
        sections: dict[str, list[str]] = {"public": [], "protected": [], "private": []}
        if c["name"] in has_children or is_iface:
            sections["public"].append(f"virtual ~{c['name']}() = default;")
        for a in c["attributes"]:
            sections[a["visibility"] if a["visibility"] in sections else "public"].append(
                f"{ct(a['type'])} {_safe(a['name'])};")
        for m in c["methods"]:
            params = ", ".join(f"{ct(p['type'])} {_safe(p['name'])}" for p in m["params"])
            sig = f"{ct(m['return_type'])} {_safe(m['name'])}({params})"
            sect = sections[m["visibility"] if m["visibility"] in sections else "public"]
            if is_iface:
                sect.append(f"virtual {sig} = 0;")
            else:
                sect.append(f'{sig} {{ throw std::logic_error("Not implemented: {c["name"]}::{m["name"]}"); }}')
        for sect, items in sections.items():
            if items:
                lines.append(f"{sect}:")
                lines += [f"{IND}{i}" for i in items]
        lines += ["};", ""]
    return "\n".join(lines)


def _uml_c(ordered, names, parents, ir):
    def ct(t):
        k = _kind(t, names)
        return {"int": "int", "float": "double", "str": "char *", "bool": "bool", "void": "void"}.get(k) or (
            "struct " + k.split(":")[1] + " *" if k.startswith("class:") else "void *")

    def default(t):
        k = _kind(t, names)
        return {"int": "0", "float": "0.0", "bool": "false"}.get(k, "NULL")

    lines = _req_header("c") + ["", "#include <stdbool.h>", "#include <stddef.h>", ""]
    lines += [f"typedef struct {c['name']} {c['name']};" for c in ordered] + [""]
    for c in ordered:
        par = parents[c["name"]]["extends"] + parents[c["name"]]["implements"]
        lines.append(f"struct {c['name']} {{")
        for n in _notes(ir, c["name"]):
            lines.append(f"{IND}/* {n} */")
        if par:
            lines.append(f"{IND}{par[0]} base; /* inherits from {par[0]} */")
            for extra in par[1:]:
                lines.append(f"{IND}/* also inherits from {extra}: not expressible in C, adapt manually */")
        for a in c["attributes"]:
            lines.append(f"{IND}{ct(a['type'])}{'' if ct(a['type']).endswith('*') else ' '}{_safe(a['name'])};")
        if not c["attributes"] and not par:
            lines.append(f"{IND}char _placeholder; /* C forbids empty structs */")
        lines += ["};", ""]
    for c in ordered:
        for m in c["methods"]:
            ret = ct(m["return_type"])
            params = "".join(f", {ct(p['type'])}{'' if ct(p['type']).endswith('*') else ' '}{_safe(p['name'])}"
                             for p in m["params"])
            lines.append(f"{ret}{'' if ret.endswith('*') else ' '}{c['name']}_{m['name']}({c['name']} *self{params}) {{")
            lines.append(f"{IND}(void)self;")
            for p in m["params"]:
                lines.append(f"{IND}(void){_safe(p['name'])};")
            lines.append(f"{IND}/* TODO: not described in the diagram */")
            if ret.strip() != "void":
                lines.append(f"{IND}return {default(m['return_type'])};")
            lines += ["}", ""]
    return "\n".join(lines)


def _uml_js(ordered, names, parents, ir):
    lines = _req_header("javascript") + ['"use strict";', ""]
    for c in ordered:
        par = parents[c["name"]]["extends"] + parents[c["name"]]["implements"]
        lines.append(f"class {c['name']}" + (f" extends {par[0]}" if par else "") + " {")
        for extra in par[1:]:
            lines.append(f"{IND}// Also inherits from {extra}: JavaScript allows one base class; adapt manually")
        for n in _notes(ir, c["name"]):
            lines.append(f"{IND}// {n}")
        if c["attributes"] or par:
            lines.append(f"{IND}constructor() {{")
            if par:
                lines.append(f"{IND*2}super();")
            for a in c["attributes"]:
                lines.append(f"{IND*2}this.{_safe(a['name'])} = null; // {a['type'] or 'unspecified'} ({a['visibility']})")
            lines.append(f"{IND}}}")
        for m in c["methods"]:
            params = ", ".join(_safe(p["name"]) for p in m["params"])
            lines.append(f"{IND}{_safe(m['name'])}({params}) {{")
            lines.append(f'{IND*2}throw new Error("Not implemented: {c["name"]}.{m["name"]}");')
            lines.append(f"{IND}}}")
        lines += ["}", ""]
    lines.append("module.exports = { " + ", ".join(c["name"] for c in ordered) + " };")
    return "\n".join(lines) + "\n"


# =========================================================================== architecture
def _q(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_architecture(ir: dict, language: str, requirement: str = "") -> str:
    comps, conns = ir["components"], ir["connections"]
    fn = {"python": _arch_python, "java": _arch_java, "cpp": _arch_cpp, "c": _arch_c, "javascript": _arch_js}[language]
    return fn(comps, conns)


def _arch_header(language: str) -> list[str]:
    c = "#" if language == "python" else "//"
    return [f"{c} Component scaffold generated by Syntax AI from an architecture diagram.",
            f"{c} Only the components and connections visible in the diagram are modelled; no business logic is invented."]


def _arch_python(comps, conns):
    lines = ['"""Component scaffold generated by Syntax AI from an architecture diagram.',
             'Only the components and connections visible in the diagram are modelled."""', "",
             "", "class Component:",
             f"{IND}def __init__(self, name, kind, description=\"\"):",
             f"{IND*2}self.name = name", f"{IND*2}self.kind = kind", f"{IND*2}self.description = description",
             f"{IND*2}self.dependencies = []  # (component, label)", "",
             f"{IND}def connect(self, other, label=\"\"):", f"{IND*2}self.dependencies.append((other, label))"]
    for c in comps:
        lines += ["", "", f"class {c['name']}(Component):",
                  f'{IND}"""{c["type"]}' + (f": {c['description'].replace(chr(34), chr(39))}" if c["description"] else "") + '"""', "",
                  f"{IND}def __init__(self):",
                  f"{IND*2}super().__init__({_q(c['name'])}, {_q(c['type'])}, {_q(c['description'])})"]
    lines += ["", "", "def build_system():", f'{IND}"""Create every component and wire the connections shown in the diagram."""']
    for c in comps:
        lines.append(f"{IND}{_snake(c['name'])} = {c['name']}()")
    for k in conns:
        lines.append(f"{IND}{_snake(k['from'])}.connect({_snake(k['to'])}, {_q(k['label'])})")
    lines.append(f"{IND}return [{', '.join(_snake(c['name']) for c in comps)}]")
    lines += ["", "", 'if __name__ == "__main__":', f"{IND}for component in build_system():",
              f"{IND*2}for other, label in component.dependencies:",
              f'{IND*3}print(f"{{component.name}} -> {{other.name}}" + (f" ({{label}})" if label else ""))']
    return "\n".join(lines) + "\n"


def _arch_java(comps, conns):
    lines = _arch_header("java") + ["", "import java.util.ArrayList;", "import java.util.List;", "",
             "class Component {", f"{IND}final String name;", f"{IND}final String kind;", f"{IND}final String description;",
             f"{IND}final List<Component> dependencies = new ArrayList<>();",
             f"{IND}final List<String> labels = new ArrayList<>();", "",
             f"{IND}Component(String name, String kind, String description) {{",
             f"{IND*2}this.name = name; this.kind = kind; this.description = description;", f"{IND}}}", "",
             f"{IND}void connect(Component other, String label) {{",
             f"{IND*2}dependencies.add(other); labels.add(label);", f"{IND}}}", "}", ""]
    for c in comps:
        lines += [f"class {c['name']} extends Component {{",
                  f"{IND}{c['name']}() {{ super({_q(c['name'])}, {_q(c['type'])}, {_q(c['description'])}); }}", "}", ""]
    lines += ["public class Main {", f"{IND}static List<Component> buildSystem() {{"]
    for c in comps:
        lines.append(f"{IND*2}{c['name']} {_camel(c['name'])} = new {c['name']}();")
    for k in conns:
        lines.append(f"{IND*2}{_camel(k['from'])}.connect({_camel(k['to'])}, {_q(k['label'])});")
    lines.append(f"{IND*2}List<Component> all = new ArrayList<>();")
    for c in comps:
        lines.append(f"{IND*2}all.add({_camel(c['name'])});")
    lines += [f"{IND*2}return all;", f"{IND}}}", "",
              f"{IND}public static void main(String[] args) {{",
              f"{IND*2}for (Component c : buildSystem()) {{",
              f"{IND*3}for (int i = 0; i < c.dependencies.size(); i++) {{",
              f'{IND*4}String label = c.labels.get(i).isEmpty() ? "" : " (" + c.labels.get(i) + ")";',
              f'{IND*4}System.out.println(c.name + " -> " + c.dependencies.get(i).name + label);',
              f"{IND*3}}}", f"{IND*2}}}", f"{IND}}}", "}"]
    return "\n".join(lines) + "\n"


def _arch_cpp(comps, conns):
    lines = _arch_header("cpp") + ["", "#include <iostream>", "#include <memory>", "#include <string>",
             "#include <utility>", "#include <vector>", "",
             "class Component {", "public:", f"{IND}std::string name, kind, description;",
             f"{IND}std::vector<std::pair<Component*, std::string>> dependencies;",
             f"{IND}Component(std::string n, std::string k, std::string d)",
             f"{IND*2}: name(std::move(n)), kind(std::move(k)), description(std::move(d)) {{}}",
             f"{IND}virtual ~Component() = default;",
             f"{IND}void connect(Component* other, const std::string& label = \"\") {{ dependencies.emplace_back(other, label); }}",
             "};", ""]
    for c in comps:
        lines += [f"class {c['name']} : public Component {{", "public:",
                  f"{IND}{c['name']}() : Component({_q(c['name'])}, {_q(c['type'])}, {_q(c['description'])}) {{}}", "};", ""]
    lines += ["std::vector<std::unique_ptr<Component>> buildSystem() {", f"{IND}std::vector<std::unique_ptr<Component>> all;"]
    for c in comps:
        lines.append(f"{IND}all.push_back(std::make_unique<{c['name']}>());")
    idx = {c["name"]: i for i, c in enumerate(comps)}
    for k in conns:
        lines.append(f"{IND}all[{idx[k['from']]}]->connect(all[{idx[k['to']]}].get(), {_q(k['label'])});")
    lines += [f"{IND}return all;", "}", "", "int main() {", f"{IND}auto system = buildSystem();",
              f"{IND}for (const auto& c : system) {{", f"{IND*2}for (const auto& d : c->dependencies) {{",
              f'{IND*3}std::cout << c->name << " -> " << d.first->name'
              f' << (d.second.empty() ? "" : " (" + d.second + ")") << std::endl;',
              f"{IND*2}}}", f"{IND}}}", f"{IND}return 0;", "}"]
    return "\n".join(lines) + "\n"


def _arch_c(comps, conns):
    lines = _arch_header("c") + ["", "#include <stdio.h>", "", "#define MAX_DEPENDENCIES 16", "",
             "typedef struct Component {", f"{IND}const char *name;", f"{IND}const char *kind;", f"{IND}const char *description;",
             f"{IND}struct Component *dependencies[MAX_DEPENDENCIES];", f"{IND}const char *labels[MAX_DEPENDENCIES];",
             f"{IND}int dependency_count;", "} Component;", "",
             "static void connect(Component *from, Component *to, const char *label) {",
             f"{IND}if (from->dependency_count < MAX_DEPENDENCIES) {{",
             f"{IND*2}from->dependencies[from->dependency_count] = to;",
             f"{IND*2}from->labels[from->dependency_count] = label;",
             f"{IND*2}from->dependency_count++;", f"{IND}}}", "}", ""]
    for c in comps:
        lines.append(f"static Component {_snake(c['name'])} = {{{_q(c['name'])}, {_q(c['type'])}, {_q(c['description'])}, {{0}}, {{0}}, 0}};")
    lines += ["", "int main(void) {"]
    for k in conns:
        lines.append(f"{IND}connect(&{_snake(k['from'])}, &{_snake(k['to'])}, {_q(k['label'])});")
    lines.append(f"{IND}Component *all[] = {{{', '.join('&' + _snake(c['name']) for c in comps)}}};")
    lines += [f"{IND}for (int i = 0; i < {len(comps)}; i++) {{",
              f"{IND*2}for (int j = 0; j < all[i]->dependency_count; j++) {{",
              f'{IND*3}printf("%s -> %s%s%s%s\\n", all[i]->name, all[i]->dependencies[j]->name,',
              f'{IND*4}all[i]->labels[j][0] ? " (" : "", all[i]->labels[j], all[i]->labels[j][0] ? ")" : "");',
              f"{IND*2}}}", f"{IND}}}", f"{IND}return 0;", "}"]
    return "\n".join(lines) + "\n"


def _arch_js(comps, conns):
    lines = _arch_header("javascript") + ['"use strict";', "", "class Component {",
             f"{IND}constructor(name, kind, description = \"\") {{",
             f"{IND*2}this.name = name; this.kind = kind; this.description = description;",
             f"{IND*2}this.dependencies = []; // {{ component, label }}", f"{IND}}}",
             f"{IND}connect(other, label = \"\") {{ this.dependencies.push({{ component: other, label }}); }}", "}", ""]
    for c in comps:
        lines += [f"class {c['name']} extends Component {{",
                  f"{IND}constructor() {{ super({_q(c['name'])}, {_q(c['type'])}, {_q(c['description'])}); }}", "}", ""]
    lines += ["function buildSystem() {"]
    for c in comps:
        lines.append(f"{IND}const {_camel(c['name'])} = new {c['name']}();")
    for k in conns:
        lines.append(f"{IND}{_camel(k['from'])}.connect({_camel(k['to'])}, {_q(k['label'])});")
    lines += [f"{IND}return [{', '.join(_camel(c['name']) for c in comps)}];", "}", "",
              "if (require.main === module) {", f"{IND}for (const c of buildSystem()) {{",
              f"{IND*2}for (const d of c.dependencies) {{",
              f"{IND*3}console.log(`${{c.name}} -> ${{d.component.name}}${{d.label ? ` (${{d.label}})` : \"\"}}`);",
              f"{IND*2}}}", f"{IND}}}", "}", "",
              "module.exports = { Component, buildSystem, " + ", ".join(c["name"] for c in comps) + " };"]
    return "\n".join(lines) + "\n"
